/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views.temas;

/**
 *
 * @author Usuario
 */
public class pnlTema1 extends javax.swing.JPanel {

    /**
     * Creates new form pnlTema1
     */
    public pnlTema1() {
        initComponents();
        this.setSize(180,174);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTema1 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(180, 174));
        setMinimumSize(new java.awt.Dimension(180, 174));
        setPreferredSize(new java.awt.Dimension(180, 174));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTema1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/temaClaro.png"))); // NOI18N
        lblTema1.setText("jLabel1");
        add(lblTema1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 180));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblTema1;
    // End of variables declaration//GEN-END:variables
}
