package views;

import controllers.ExamenPrincipalController;
import controllers.examen.ExamenController;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import org.jdesktop.swingx.border.DropShadowBorder;

public class Examen extends javax.swing.JInternalFrame {

    public Examen() {
        initComponents();
        this.setSize(622, 408);
        ((BasicInternalFrameUI) this.getUI()).setNorthPane(null);
        setBorderInternal();
        setUpControllers();
    }

    private void setUpControllers() {

        ec = new ExamenPrincipalController(this);
        btnEmpezarExamen.addActionListener(ec);

    }

    private ExamenPrincipalController ec;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void setBorderInternal() {
        DropShadowBorder border = (DropShadowBorder) this.getBorder();
        border.setShowBottomShadow(false);
        border.setShowRightShadow(true);
        border.setShowLeftShadow(true);
        border.setShowTopShadow(true);
        border.setShadowSize(15);
    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnEmpezarExamen = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBorder(new org.jdesktop.swingx.border.DropShadowBorder());
        setMaximumSize(new java.awt.Dimension(622, 408));
        setMinimumSize(new java.awt.Dimension(622, 408));
        setPreferredSize(new java.awt.Dimension(622, 408));
        getContentPane().setLayout(null);

        btnEmpezarExamen.setBackground(new java.awt.Color(0, 0, 0));
        btnEmpezarExamen.setForeground(new java.awt.Color(255, 255, 255));
        btnEmpezarExamen.setText("Empezar examen");
        getContentPane().add(btnEmpezarExamen);
        btnEmpezarExamen.setBounds(210, 180, 210, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/fondoOM.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 620, 390);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void redimensionar(boolean redimensionar) {
        if (redimensionar) {

        } else {

        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton btnEmpezarExamen;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
