/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import javax.swing.UIManager;

/**
 *
 * @author Usuario
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktop = new javax.swing.JDesktopPane();
        pnlLogo = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        pnlMenu = new javax.swing.JPanel();
        pnlMostrarMenu = new javax.swing.JPanel();
        lblMenu = new javax.swing.JLabel();
        pnlExamen = new javax.swing.JPanel();
        lblExamen = new javax.swing.JLabel();
        lblIconoExamen = new javax.swing.JLabel();
        pnlIniciarSesion1 = new javax.swing.JPanel();
        lblInicioSesion = new javax.swing.JLabel();
        lblIconoUsuario = new javax.swing.JLabel();
        pnlAjustes = new javax.swing.JPanel();
        lblAjustes = new javax.swing.JLabel();
        lblIconoAjustes = new javax.swing.JLabel();
        pnlResolver = new javax.swing.JPanel();
        lblResolver = new javax.swing.JLabel();
        lblIconoResolver = new javax.swing.JLabel();
        pnlDocumentos1 = new javax.swing.JPanel();
        lblDocumentos = new javax.swing.JLabel();
        lblIconoDocumentos = new javax.swing.JLabel();
        pnlPractica1 = new javax.swing.JPanel();
        lblPractica = new javax.swing.JLabel();
        lblIconoPractica = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        internalFrame = new javax.swing.JInternalFrame();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(774, 581));
        setPreferredSize(new java.awt.Dimension(774, 581));

        desktop.setBackground(new java.awt.Color(0, 0, 0));
        desktop.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout pnlLogoLayout = new javax.swing.GroupLayout(pnlLogo);
        pnlLogo.setLayout(pnlLogoLayout);
        pnlLogoLayout.setHorizontalGroup(
            pnlLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblLogo, javax.swing.GroupLayout.DEFAULT_SIZE, 774, Short.MAX_VALUE)
        );
        pnlLogoLayout.setVerticalGroup(
            pnlLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblLogo, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        desktop.add(pnlLogo, java.awt.BorderLayout.PAGE_START);

        pnlMenu.setPreferredSize(new java.awt.Dimension(250, 470));
        pnlMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlMostrarMenu.setMinimumSize(new java.awt.Dimension(60, 476));

        lblMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/icons8-menu-48.png"))); // NOI18N

        javax.swing.GroupLayout pnlMostrarMenuLayout = new javax.swing.GroupLayout(pnlMostrarMenu);
        pnlMostrarMenu.setLayout(pnlMostrarMenuLayout);
        pnlMostrarMenuLayout.setHorizontalGroup(
            pnlMostrarMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMostrarMenuLayout.createSequentialGroup()
                .addComponent(lblMenu, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlMostrarMenuLayout.setVerticalGroup(
            pnlMostrarMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMostrarMenuLayout.createSequentialGroup()
                .addComponent(lblMenu)
                .addGap(0, 428, Short.MAX_VALUE))
        );

        pnlMenu.add(pnlMostrarMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 476));

        pnlExamen.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblExamen.setText("Examen");

        lblIconoExamen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/icons8-test-passed-35.png"))); // NOI18N

        javax.swing.GroupLayout pnlExamenLayout = new javax.swing.GroupLayout(pnlExamen);
        pnlExamen.setLayout(pnlExamenLayout);
        pnlExamenLayout.setHorizontalGroup(
            pnlExamenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlExamenLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblIconoExamen)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(lblExamen, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlExamenLayout.setVerticalGroup(
            pnlExamenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlExamenLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(pnlExamenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblIconoExamen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblExamen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pnlMenu.add(pnlExamen, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, 190, 60));

        pnlIniciarSesion1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblInicioSesion.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblInicioSesion.setText("Iniciar sesión");

        lblIconoUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/icons8-male-user-35.png"))); // NOI18N

        javax.swing.GroupLayout pnlIniciarSesion1Layout = new javax.swing.GroupLayout(pnlIniciarSesion1);
        pnlIniciarSesion1.setLayout(pnlIniciarSesion1Layout);
        pnlIniciarSesion1Layout.setHorizontalGroup(
            pnlIniciarSesion1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlIniciarSesion1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblIconoUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(lblInicioSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlIniciarSesion1Layout.setVerticalGroup(
            pnlIniciarSesion1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlIniciarSesion1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlIniciarSesion1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblInicioSesion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblIconoUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pnlMenu.add(pnlIniciarSesion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 190, 60));

        pnlAjustes.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblAjustes.setText("Ajustes");

        lblIconoAjustes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/icons8-settings-35.png"))); // NOI18N

        javax.swing.GroupLayout pnlAjustesLayout = new javax.swing.GroupLayout(pnlAjustes);
        pnlAjustes.setLayout(pnlAjustesLayout);
        pnlAjustesLayout.setHorizontalGroup(
            pnlAjustesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAjustesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblIconoAjustes, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(lblAjustes, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlAjustesLayout.setVerticalGroup(
            pnlAjustesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAjustesLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(pnlAjustesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblIconoAjustes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblAjustes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pnlMenu.add(pnlAjustes, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 190, 60));

        pnlResolver.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblResolver.setText("Resolver");

        lblIconoResolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/icons8-approve-35.png"))); // NOI18N

        javax.swing.GroupLayout pnlResolverLayout = new javax.swing.GroupLayout(pnlResolver);
        pnlResolver.setLayout(pnlResolverLayout);
        pnlResolverLayout.setHorizontalGroup(
            pnlResolverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlResolverLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblIconoResolver, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(lblResolver, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlResolverLayout.setVerticalGroup(
            pnlResolverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlResolverLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlResolverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblIconoResolver, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblResolver, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(10, 10, 10))
        );

        pnlMenu.add(pnlResolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 190, 60));

        pnlDocumentos1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblDocumentos.setText("Documentos");

        lblIconoDocumentos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/icons8-documents-35.png"))); // NOI18N

        javax.swing.GroupLayout pnlDocumentos1Layout = new javax.swing.GroupLayout(pnlDocumentos1);
        pnlDocumentos1.setLayout(pnlDocumentos1Layout);
        pnlDocumentos1Layout.setHorizontalGroup(
            pnlDocumentos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDocumentos1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblIconoDocumentos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(lblDocumentos, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlDocumentos1Layout.setVerticalGroup(
            pnlDocumentos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDocumentos1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(pnlDocumentos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblIconoDocumentos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblDocumentos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pnlMenu.add(pnlDocumentos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 190, 60));

        pnlPractica1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblPractica.setText("Práctica");

        lblIconoPractica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/icons8-pencil-35.png"))); // NOI18N

        javax.swing.GroupLayout pnlPractica1Layout = new javax.swing.GroupLayout(pnlPractica1);
        pnlPractica1.setLayout(pnlPractica1Layout);
        pnlPractica1Layout.setHorizontalGroup(
            pnlPractica1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPractica1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblIconoPractica)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(lblPractica, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlPractica1Layout.setVerticalGroup(
            pnlPractica1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPractica1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(pnlPractica1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblIconoPractica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblPractica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pnlMenu.add(pnlPractica1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 190, 60));

        desktop.add(pnlMenu, java.awt.BorderLayout.LINE_START);

        jPanel4.setLayout(new java.awt.BorderLayout());

        jPanel6.setPreferredSize(new java.awt.Dimension(10, 10));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 466, Short.MAX_VALUE)
        );

        jPanel4.add(jPanel6, java.awt.BorderLayout.LINE_START);

        jPanel7.setPreferredSize(new java.awt.Dimension(10, 10));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 466, Short.MAX_VALUE)
        );

        jPanel4.add(jPanel7, java.awt.BorderLayout.LINE_END);

        jPanel8.setPreferredSize(new java.awt.Dimension(10, 10));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 524, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jPanel4.add(jPanel8, java.awt.BorderLayout.PAGE_END);

        internalFrame.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        internalFrame.setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        internalFrame.setVisible(true);
        internalFrame.getContentPane().setLayout(new java.awt.CardLayout());
        jPanel4.add(internalFrame, java.awt.BorderLayout.CENTER);

        desktop.add(jPanel4, java.awt.BorderLayout.CENTER);

        getContentPane().add(desktop, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            UIManager.setLookAndFeel("com.jtattoo.plaf.noire.NoireLookAndFeel");
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktop;
    private javax.swing.JInternalFrame internalFrame;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JLabel lblAjustes;
    private javax.swing.JLabel lblDocumentos;
    private javax.swing.JLabel lblExamen;
    private javax.swing.JLabel lblIconoAjustes;
    private javax.swing.JLabel lblIconoDocumentos;
    private javax.swing.JLabel lblIconoExamen;
    private javax.swing.JLabel lblIconoPractica;
    private javax.swing.JLabel lblIconoResolver;
    private javax.swing.JLabel lblIconoUsuario;
    private javax.swing.JLabel lblInicioSesion;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblMenu;
    private javax.swing.JLabel lblPractica;
    private javax.swing.JLabel lblResolver;
    private javax.swing.JPanel pnlAjustes;
    private javax.swing.JPanel pnlDocumentos1;
    private javax.swing.JPanel pnlExamen;
    private javax.swing.JPanel pnlIniciarSesion1;
    private javax.swing.JPanel pnlLogo;
    private javax.swing.JPanel pnlMenu;
    private javax.swing.JPanel pnlMostrarMenu;
    private javax.swing.JPanel pnlPractica1;
    private javax.swing.JPanel pnlResolver;
    // End of variables declaration//GEN-END:variables
}
