/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views.funcion;


import controllers.examen.ExamenController;
import java.awt.Toolkit;
import javax.swing.JOptionPane;
import models.examen.Cronometro;
import models.examen.DatosExamen;

/**
 *
 * @author Kenneth Granados
 */
public class ExamenFrame extends javax.swing.JInternalFrame {
    ExamenController ec;
     public static int hora=0,minutos=0,segundos=0;
    public static boolean inicio=true;
     boolean corriendo=false;
    
    public ExamenFrame() {
        this.setSize(622,408);
        initComponents();
        setupController();
        String[] b = de.setSepRespuesta(pos);
        questionLabel.setText(de.getPregunta(0));
            buttonGroup1.clearSelection();
            resp1RadioButton.setText(b[0]);
            resp2RadioButton.setText(b[1]);
            resp3RadioButton.setText(b[2]);
            resp4RadioButton.setText(b[3]);
            resp1RadioButton.requestFocus();
    }

    public final void setupController(){
        ec = new ExamenController(this);
        regresarButton.addActionListener(ec);
        avanzarButton.addActionListener(ec);
        terminarButton.addActionListener(ec);
    }
    int pos=0;
    DatosExamen de= new DatosExamen();
    Object [] select ={"","","","","" };
    
    public void AvanceData(){
       
        if (pos <5 ) {
            pos++;
            questionLabel.setText(de.getPregunta(pos));
            String[] b = de.setSepRespuesta(pos);
            buttonGroup1.clearSelection();
            resp1RadioButton.setText(b[0]);
            resp2RadioButton.setText(b[1]);
            resp3RadioButton.setText(b[2]);
            resp4RadioButton.setText(b[3]);
            resp1RadioButton.requestFocus();
        } else {
            Toolkit.getDefaultToolkit().beep();
            JOptionPane.showMessageDialog(null, "Ya no hay mas preguntas");
        }
 
    }
    
    public void RegresarData(){
 
        if (pos >0) {
             pos--;
        } else {
          
        }
        
        if (pos > -1) {
           questionLabel.setText(de.getPregunta(pos));
            String[] b = de.setSepRespuesta(pos);
            buttonGroup1.clearSelection();
            resp1RadioButton.setText(b[0]);
            resp2RadioButton.setText(b[1]);
            resp3RadioButton.setText(b[2]);
            resp4RadioButton.setText(b[3]);
            resp1RadioButton.requestFocus();
        } else {
             Toolkit.getDefaultToolkit().beep();
             JOptionPane.showMessageDialog(null, "No se puede regresar");
        }
    }
    
    public void Resultado() {
        
        int calif=0;
        for (int i = 0; i < 5; i++) {
            if (select[i].equals(de.getRespuesta(i))) {
                calif= calif + 1;
            }
        }
        calif= calif * 2;
        JOptionPane.showMessageDialog(null, "La calificacion es: "+calif);
    }
    
    public void InicioTiempo(){
        if (corriendo==false) {
            inicio=true;
            corriendo=false;
            iniciarCronometro();
        }
    }
    
     public void FinTiempo(){
            inicio=false;
            corriendo=false;
             hora=0;
            minutos=0;
           segundos=0;
    }
  
     public void iniciarCronometro() {
         if (inicio==true) {
             Cronometro c = new Cronometro(cronometroLabel);
             c.start();
             
         }
         
     }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        questionLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        resp1RadioButton = new javax.swing.JRadioButton();
        resp3RadioButton = new javax.swing.JRadioButton();
        resp4RadioButton = new javax.swing.JRadioButton();
        resp2RadioButton = new javax.swing.JRadioButton();
        avanzarButton = new javax.swing.JButton();
        regresarButton = new javax.swing.JButton();
        terminarButton = new javax.swing.JButton();
        cronometroLabel = new javax.swing.JLabel();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Examen");
        setMaximumSize(new java.awt.Dimension(622, 408));
        setMinimumSize(new java.awt.Dimension(622, 408));
        setPreferredSize(new java.awt.Dimension(622, 408));

        questionLabel.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        questionLabel.setForeground(new java.awt.Color(255, 255, 255));
        questionLabel.setText("Pregunta?");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Pregunta");

        buttonGroup1.add(resp1RadioButton);
        resp1RadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resp1RadioButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(resp3RadioButton);
        resp3RadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resp3RadioButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(resp4RadioButton);
        resp4RadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resp4RadioButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(resp2RadioButton);
        resp2RadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resp2RadioButtonActionPerformed(evt);
            }
        });

        avanzarButton.setText("Avanzar>>");
        avanzarButton.setToolTipText("");
        avanzarButton.setActionCommand("Avanzar");

        regresarButton.setText("<<Regresar");
        regresarButton.setActionCommand("Regresar");

        terminarButton.setText("Terminar");

        cronometroLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        cronometroLabel.setText("00:00:00");
        cronometroLabel.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(resp2RadioButton)
                            .addComponent(resp4RadioButton)
                            .addComponent(resp3RadioButton)
                            .addComponent(resp1RadioButton))
                        .addGap(137, 586, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                            .addComponent(questionLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cronometroLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(regresarButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(terminarButton)
                        .addGap(124, 124, 124)
                        .addComponent(avanzarButton)
                        .addGap(85, 85, 85))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cronometroLabel))
                .addGap(16, 16, 16)
                .addComponent(questionLabel)
                .addGap(23, 23, 23)
                .addComponent(resp1RadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(resp2RadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(resp3RadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(resp4RadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 141, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(regresarButton)
                    .addComponent(terminarButton)
                    .addComponent(avanzarButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void resp1RadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resp1RadioButtonActionPerformed
     select[pos] = resp1RadioButton.getLabel();
    }//GEN-LAST:event_resp1RadioButtonActionPerformed

    private void resp2RadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resp2RadioButtonActionPerformed
       select[pos] = resp2RadioButton.getLabel();
    }//GEN-LAST:event_resp2RadioButtonActionPerformed

    private void resp3RadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resp3RadioButtonActionPerformed
        select[pos] = resp3RadioButton.getLabel();
    }//GEN-LAST:event_resp3RadioButtonActionPerformed

    private void resp4RadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resp4RadioButtonActionPerformed
        select[pos] = resp4RadioButton.getLabel();
    }//GEN-LAST:event_resp4RadioButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton avanzarButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel cronometroLabel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel questionLabel;
    private javax.swing.JButton regresarButton;
    public static javax.swing.JRadioButton resp1RadioButton;
    public static javax.swing.JRadioButton resp2RadioButton;
    public static javax.swing.JRadioButton resp3RadioButton;
    public static javax.swing.JRadioButton resp4RadioButton;
    private javax.swing.JButton terminarButton;
    // End of variables declaration//GEN-END:variables

}
