/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views.funcion;

import controllers.funciones.FuncionController;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import models.funciones.Funcion;
import models.funciones.GraficaFuncion;

/**
 *
 * @author Kenneth Granados
 */
public class FuncionesFrame extends javax.swing.JInternalFrame {

    FuncionController fc;
    GraficaFuncion grafica = new GraficaFuncion("Grafica", "Eje X", "Eje Y");
    
    public FuncionesFrame() {
        initComponents();
        setupController();
    }
    
    public void setupController() {
        fc = new FuncionController(this);
        graficarButton.addActionListener(fc);
        agregarButton.addActionListener(fc);
        cleanButton.addActionListener(fc);
        funcTextField.addKeyListener(fc);//action de teclado
        x0TextField.addKeyListener(fc);
        xnTextField.addKeyListener(fc);
        intervaloTextField.addKeyListener(fc);
    }
    
    public void getgrafica() throws Exception {
         try {
            String func = funcTextField.getText();
            double x0 = Double.parseDouble(x0TextField.getText());
            double xn = Double.parseDouble(xnTextField.getText());
            double d = Double.parseDouble(intervaloTextField.getText());
            Funcion f = new Funcion(func);
            double[] x = f.Rango(x0, xn, d);
            double[] y = f.evaluar(x);
            grafica.CrearGrafica(func, x, y);
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Chingue su madre" + e.getMessage());
            }
               
    
    }

    public void addgrafica() throws Exception {
        try {
            String func = funcTextField.getText();
            double x0 = Double.parseDouble(x0TextField.getText());
            double xn = Double.parseDouble(xnTextField.getText());
            double d = Double.parseDouble(intervaloTextField.getText());
            Funcion f = new Funcion(func);
            double[] x = f.Rango(x0, xn, d);
            double[] y = f.evaluar(x);
            grafica.AgregarGrafica(func, x, y);
       
        } catch (NumberFormatException ex) {
            Logger.getLogger(FuncionesFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void clean() {
        funcTextField.setText("");
        x0TextField.setText("");
        xnTextField.setText("");
        intervaloTextField.setText("");
        grafica.LimpiarGrafica();
    }

    public JTextField getFuncTextField() {
        return funcTextField;
    }

    public JTextField getX0TextField() {
        return x0TextField;
    }

    public JTextField getXnTextField() {
        return xnTextField;
    }

    public JTextField getIntervaloTextField() {
        return intervaloTextField;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        funcTextField = new javax.swing.JTextField();
        x0TextField = new javax.swing.JTextField();
        xnTextField = new javax.swing.JTextField();
        intervaloTextField = new javax.swing.JTextField();
        graficarButton = new javax.swing.JButton();
        agregarButton = new javax.swing.JButton();
        cleanButton = new javax.swing.JButton();
        Panel = grafica.ObtenerGrafica()
        ;

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Funciones");
        setPreferredSize(new java.awt.Dimension(6, 6));

        jLabel1.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jLabel1.setText("Funcion");

        jLabel2.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jLabel2.setText("Desde");

        jLabel3.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jLabel3.setText("Hasta");

        jLabel4.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jLabel4.setText("Intervalo");

        funcTextField.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        x0TextField.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        xnTextField.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        intervaloTextField.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        graficarButton.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        graficarButton.setText("Graficar");

        agregarButton.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        agregarButton.setText("Agregar");

        cleanButton.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        cleanButton.setText("Limpiar");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(53, 53, 53)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(intervaloTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                            .addComponent(xnTextField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(x0TextField, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(graficarButton, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(agregarButton, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cleanButton, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(funcTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(funcTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(x0TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(xnTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(intervaloTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(graficarButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(agregarButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cleanButton)))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout PanelLayout = new javax.swing.GroupLayout(Panel);
        Panel.setLayout(PanelLayout);
        PanelLayout.setHorizontalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 334, Short.MAX_VALUE)
        );
        PanelLayout.setVerticalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(12, 12, 12))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel;
    private javax.swing.JButton agregarButton;
    private javax.swing.JButton cleanButton;
    private javax.swing.JTextField funcTextField;
    private javax.swing.JButton graficarButton;
    private javax.swing.JTextField intervaloTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField x0TextField;
    private javax.swing.JTextField xnTextField;
    // End of variables declaration//GEN-END:variables

}
